import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: '#f8f7e3',
        padding: 20,
    },
    inputContainer: {
        marginBottom: 20,
        alignItems: 'center',
        width: '100%',
    },
    input: {
        height: 50,
        backgroundColor: '#fff',
        borderColor: '#7b1f3a',
        borderWidth: 1,
        paddingHorizontal: 20,
        borderRadius: 25,
        width: '85%',
        fontSize: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    buttonContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        marginTop: 10,
    },
    button: {
        backgroundColor: '#7b1f3a',
        width: '85%',
        borderRadius: 25,
        padding: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 3,
    },
    buttonText: {
        textAlign: 'center',
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
    },
    image: {
        width: 250,
        alignSelf: 'center',
        height: 250,
        resizeMode: 'contain',
        marginBottom: 30,
    },
    texto: {
        textAlign: 'center',
        marginTop: 25,
        fontSize: 16,
        color: '#333',
        lineHeight: 22,
    },
    link: {
        color: '#7b1f3a',
        fontWeight: 'bold',
        fontSize: 16,
    },
    titulo: {
        textAlign: 'center',
        fontSize: 32,
        fontWeight: 'bold',
        marginBottom: 30,
        color: '#7b1f3a',
        textShadowColor: 'rgba(0, 0, 0, 0.1)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 2,
    },
    containerLista: {
        padding: 15,
        width: '100%',
    },
    itemLista: {
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 15,
        marginBottom: 15,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.15,
        shadowRadius: 5,
        borderLeftWidth: 4,
        borderLeftColor: '#7b1f3a',
    },
    textoItem: {
        fontSize: 18,
        color: '#333',
        fontWeight: '500',
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: '#f8f7e3',
        borderRadius: 20,
        padding: 25,
        width: '90%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 25,
        color: '#7b1f3a',
    },
    modalInput: {
        height: 50,
        backgroundColor: '#fff',
        borderColor: '#7b1f3a',
        borderWidth: 1,
        paddingHorizontal: 20,
        borderRadius: 25,
        width: '100%',
        fontSize: 16,
        marginBottom: 15,
    },
    modalButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 25,
    },
    modalButton: {
        backgroundColor: '#7b1f3a',
        padding: 15,
        borderRadius: 25,
        width: '48%',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    modalCancelButton: {
        backgroundColor: '#FF3B30',
    },
    modalDeleteButton: {
        backgroundColor: '#FF0000',
        width: '100%',
        marginTop: 15,
    },
    modalButtonText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 16,
    },
});
